"""remove description fields from category, brand, and product

Revision ID: a1465f7808df
Revises: a799ad2ea57a
Create Date: 2026-08-11 17:18:52.074200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1465f7808df'
down_revision = 'a799ad2ea57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
