"""add inspiration_image to orders

Revision ID: f528659285a5
Revises: remove_brands_001
Create Date: 2026-08-13 15:44:54.312198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f528659285a5'
down_revision = 'remove_brands_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inspiration_image', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('inspiration_image')

    # ### end Alembic commands ###
